version: '3.1'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sem
      MYSQL_DATABASE: world
    ports:
      - "3306:3306"
    volumes:
      - ./db/world.sql:/docker-entrypoint-initdb.d/world.sql
  app:
    build: .
    depends_on:
      - db